# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fff05d4bd65e5ca43ad3a1466ae5775d79058af840ddd42b012d16013d126f0d6fd717277fde1f9bbb852c00b5b3e6b8f7da631790348254f0201f452ed7ffe9

test:
  secret_key_base: 7f06d1ddf019da769cf4a05975e8562961912cafccc1ab966b1dce27704b03574cf958f1f5f307cd50e562ff3b893df9b0aa4cab36095ffd6e5562d37dcdc7d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
